/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as AuthImport } from './routes/auth'
import { Route as AuthLoginImport } from './routes/auth/login'
import { Route as AuthRegisterImport } from './routes/auth/register'
import { Route as BandiImport } from './routes/bandi'
import { Route as CorsiImport } from './routes/corsi'
import { Route as EventiImport } from './routes/eventi'
import { Route as ProgettiImport } from './routes/progetti'
import { Route as VolontariatoImport } from './routes/volontariato'
import { Route as NewsImport } from './routes/news'
import { Route as PartnersImport } from './routes/partners'
import { Route as DashboardImport } from './routes/dashboard/index'
import { Route as DashboardAdminImport } from './routes/dashboard/admin/route'
import { Route as DashboardAdminIndexImport } from './routes/dashboard/admin/home'
import { Route as DashboardUserImport } from './routes/dashboard/user'
import { Route as DashboardPartnerImport } from './routes/dashboard/partner'
import { Route as DashboardAdminUsersImport } from './routes/dashboard/admin/users'
import { Route as DashboardAdminBandiImport } from './routes/dashboard/admin/bandi'
import { Route as DashboardAdminMatchImport } from './routes/dashboard/admin/match'
import { Route as DashboardAdminEventsImport } from './routes/dashboard/admin/events'
import { Route as DashboardAdminVolunteerImport } from './routes/dashboard/admin/volunteer'
import { Route as DashboardAdminPartnersImport } from './routes/dashboard/admin/partners'
import { Route as DashboardAdminAnalyticsImport } from './routes/dashboard/admin/analytics'
import { Route as DashboardAdminSystemImport } from './routes/dashboard/admin/system'
import { Route as DashboardAdminSecurityImport } from './routes/dashboard/admin/security'
import { Route as DashboardAdminNotificationsImport } from './routes/dashboard/admin/notifications'
import { Route as DashboardAdminSettingsImport } from './routes/dashboard/admin/settings'

// Create Virtual Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)

const AuthRegisterRoute = AuthRegisterImport.update({
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)

const BandiRoute = BandiImport.update({
  path: '/bandi',
  getParentRoute: () => rootRoute,
} as any)

const CorsiRoute = CorsiImport.update({
  path: '/corsi',
  getParentRoute: () => rootRoute,
} as any)

const EventiRoute = EventiImport.update({
  path: '/eventi',
  getParentRoute: () => rootRoute,
} as any)

const ProgettiRoute = ProgettiImport.update({
  path: '/progetti',
  getParentRoute: () => rootRoute,
} as any)

const VolontariatoRoute = VolontariatoImport.update({
  path: '/volontariato',
  getParentRoute: () => rootRoute,
} as any)

const NewsRoute = NewsImport.update({
  path: '/news',
  getParentRoute: () => rootRoute,
} as any)

const PartnersRoute = PartnersImport.update({
  path: '/partners',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const DashboardAdminRoute = DashboardAdminImport.update({
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardAdminIndexRoute = DashboardAdminIndexImport.update({
  path: '/',
  getParentRoute: () => DashboardAdminRoute,
} as any)

const DashboardUserRoute = DashboardUserImport.update({
  path: '/user',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardPartnerRoute = DashboardPartnerImport.update({
  path: '/partner',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardAdminUsersRoute = DashboardAdminUsersImport.update({
  path: '/users',
  getParentRoute: () => DashboardAdminRoute,
} as any)

const DashboardAdminBandiRoute = DashboardAdminBandiImport.update({
  path: '/bandi',
  getParentRoute: () => DashboardAdminRoute,
} as any)

const DashboardAdminMatchRoute = DashboardAdminMatchImport.update({
  path: '/match',
  getParentRoute: () => DashboardAdminRoute,
} as any)

const DashboardAdminEventsRoute = DashboardAdminEventsImport.update({
  path: '/events',
  getParentRoute: () => DashboardAdminRoute,
} as any)

const DashboardAdminVolunteerRoute = DashboardAdminVolunteerImport.update({
  path: '/volunteer',
  getParentRoute: () => DashboardAdminRoute,
} as any)

const DashboardAdminPartnersRoute = DashboardAdminPartnersImport.update({
  path: '/partners',
  getParentRoute: () => DashboardAdminRoute,
} as any)

const DashboardAdminAnalyticsRoute = DashboardAdminAnalyticsImport.update({
  path: '/analytics',
  getParentRoute: () => DashboardAdminRoute,
} as any)

const DashboardAdminSystemRoute = DashboardAdminSystemImport.update({
  path: '/system',
  getParentRoute: () => DashboardAdminRoute,
} as any)

const DashboardAdminSecurityRoute = DashboardAdminSecurityImport.update({
  path: '/security',
  getParentRoute: () => DashboardAdminRoute,
} as any)

const DashboardAdminNotificationsRoute = DashboardAdminNotificationsImport.update({
  path: '/notifications',
  getParentRoute: () => DashboardAdminRoute,
} as any)

const DashboardAdminSettingsRoute = DashboardAdminSettingsImport.update({
  path: '/settings',
  getParentRoute: () => DashboardAdminRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof AuthRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterImport
      parentRoute: typeof AuthRoute
    }
    '/bandi': {
      id: '/bandi'
      path: '/bandi'
      fullPath: '/bandi'
      preLoaderRoute: typeof BandiImport
      parentRoute: typeof rootRoute
    }
    '/corsi': {
      id: '/corsi'
      path: '/corsi'
      fullPath: '/corsi'
      preLoaderRoute: typeof CorsiImport
      parentRoute: typeof rootRoute
    }
    '/eventi': {
      id: '/eventi'
      path: '/eventi'
      fullPath: '/eventi'
      preLoaderRoute: typeof EventiImport
      parentRoute: typeof rootRoute
    }
    '/progetti': {
      id: '/progetti'
      path: '/progetti'
      fullPath: '/progetti'
      preLoaderRoute: typeof ProgettiImport
      parentRoute: typeof rootRoute
    }
    '/volontariato': {
      id: '/volontariato'
      path: '/volontariato'
      fullPath: '/volontariato'
      preLoaderRoute: typeof VolontariatoImport
      parentRoute: typeof rootRoute
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsImport
      parentRoute: typeof rootRoute
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAdminIndexImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/user': {
      id: '/dashboard/user'
      path: '/user'
      fullPath: '/dashboard/user'
      preLoaderRoute: typeof DashboardUserImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/partner': {
      id: '/dashboard/partner'
      path: '/partner'
      fullPath: '/dashboard/partner'
      preLoaderRoute: typeof DashboardPartnerImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/users': {
      id: '/dashboard/admin/users'
      path: '/users'
      fullPath: '/dashboard/admin/users'
      preLoaderRoute: typeof DashboardAdminUsersImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/bandi': {
      id: '/dashboard/admin/bandi'
      path: '/bandi'
      fullPath: '/dashboard/admin/bandi'
      preLoaderRoute: typeof DashboardAdminBandiImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/match': {
      id: '/dashboard/admin/match'
      path: '/match'
      fullPath: '/dashboard/admin/match'
      preLoaderRoute: typeof DashboardAdminMatchImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/events': {
      id: '/dashboard/admin/events'
      path: '/events'
      fullPath: '/dashboard/admin/events'
      preLoaderRoute: typeof DashboardAdminEventsImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/volunteer': {
      id: '/dashboard/admin/volunteer'
      path: '/volunteer'
      fullPath: '/dashboard/admin/volunteer'
      preLoaderRoute: typeof DashboardAdminVolunteerImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/partners': {
      id: '/dashboard/admin/partners'
      path: '/partners'
      fullPath: '/dashboard/admin/partners'
      preLoaderRoute: typeof DashboardAdminPartnersImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/analytics': {
      id: '/dashboard/admin/analytics'
      path: '/analytics'
      fullPath: '/dashboard/admin/analytics'
      preLoaderRoute: typeof DashboardAdminAnalyticsImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/system': {
      id: '/dashboard/admin/system'
      path: '/system'
      fullPath: '/dashboard/admin/system'
      preLoaderRoute: typeof DashboardAdminSystemImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/security': {
      id: '/dashboard/admin/security'
      path: '/security'
      fullPath: '/dashboard/admin/security'
      preLoaderRoute: typeof DashboardAdminSecurityImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/notifications': {
      id: '/dashboard/admin/notifications'
      path: '/notifications'
      fullPath: '/dashboard/admin/notifications'
      preLoaderRoute: typeof DashboardAdminNotificationsImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/settings': {
      id: '/dashboard/admin/settings'
      path: '/settings'
      fullPath: '/dashboard/admin/settings'
      preLoaderRoute: typeof DashboardAdminSettingsImport
      parentRoute: typeof DashboardAdminRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  AuthRoute: AuthRoute.addChildren({
    AuthLoginRoute,
    AuthRegisterRoute,
  }),
  BandiRoute,
  CorsiRoute,
  EventiRoute,
  ProgettiRoute,
  VolontariatoRoute,
  NewsRoute,
  PartnersRoute,
  DashboardRoute: DashboardRoute.addChildren({
    DashboardAdminRoute: DashboardAdminRoute.addChildren({
      DashboardAdminIndexRoute,
      DashboardAdminUsersRoute,
      DashboardAdminBandiRoute,
      DashboardAdminMatchRoute,
      DashboardAdminEventsRoute,
      DashboardAdminVolunteerRoute,
      DashboardAdminPartnersRoute,
      DashboardAdminAnalyticsRoute,
      DashboardAdminSystemRoute,
      DashboardAdminSecurityRoute,
      DashboardAdminNotificationsRoute,
      DashboardAdminSettingsRoute,
    }),
    DashboardUserRoute,
    DashboardPartnerRoute,
  }),
})

/* prettier-ignore-end */
