/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const WorkoutLazyRouteImport = createFileRoute('/workout')()
const WizardLazyRouteImport = createFileRoute('/wizard')()
const RegisterLazyRouteImport = createFileRoute('/register')()
const RecipesLazyRouteImport = createFileRoute('/recipes')()
const ProgressLazyRouteImport = createFileRoute('/progress')()
const ProfileLazyRouteImport = createFileRoute('/profile')()
const PainTrackerLazyRouteImport = createFileRoute('/pain-tracker')()
const NutritionCoachLazyRouteImport = createFileRoute('/nutrition-coach')()
const NutritionLazyRouteImport = createFileRoute('/nutrition')()
const MedicalLazyRouteImport = createFileRoute('/medical')()
const LoginLazyRouteImport = createFileRoute('/login')()
const IconGeneratorLazyRouteImport = createFileRoute('/icon-generator')()
const ExercisesLazyRouteImport = createFileRoute('/exercises')()
const CoachLazyRouteImport = createFileRoute('/coach')()
const BiometricsLazyRouteImport = createFileRoute('/biometrics')()
const IndexLazyRouteImport = createFileRoute('/')()
const RecipesCreateLazyRouteImport = createFileRoute('/recipes/create')()

const WorkoutLazyRoute = WorkoutLazyRouteImport.update({
  id: '/workout',
  path: '/workout',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/workout.lazy').then((d) => d.Route))
const WizardLazyRoute = WizardLazyRouteImport.update({
  id: '/wizard',
  path: '/wizard',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/wizard.lazy').then((d) => d.Route))
const RegisterLazyRoute = RegisterLazyRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/register.lazy').then((d) => d.Route))
const RecipesLazyRoute = RecipesLazyRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/recipes.lazy').then((d) => d.Route))
const ProgressLazyRoute = ProgressLazyRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/progress.lazy').then((d) => d.Route))
const ProfileLazyRoute = ProfileLazyRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/profile.lazy').then((d) => d.Route))
const PainTrackerLazyRoute = PainTrackerLazyRouteImport.update({
  id: '/pain-tracker',
  path: '/pain-tracker',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/pain-tracker.lazy').then((d) => d.Route))
const NutritionCoachLazyRoute = NutritionCoachLazyRouteImport.update({
  id: '/nutrition-coach',
  path: '/nutrition-coach',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/nutrition-coach.lazy').then((d) => d.Route),
)
const NutritionLazyRoute = NutritionLazyRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/nutrition.lazy').then((d) => d.Route))
const MedicalLazyRoute = MedicalLazyRouteImport.update({
  id: '/medical',
  path: '/medical',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/medical.lazy').then((d) => d.Route))
const LoginLazyRoute = LoginLazyRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))
const IconGeneratorLazyRoute = IconGeneratorLazyRouteImport.update({
  id: '/icon-generator',
  path: '/icon-generator',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/icon-generator.lazy').then((d) => d.Route),
)
const ExercisesLazyRoute = ExercisesLazyRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/exercises.lazy').then((d) => d.Route))
const CoachLazyRoute = CoachLazyRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/coach.lazy').then((d) => d.Route))
const BiometricsLazyRoute = BiometricsLazyRouteImport.update({
  id: '/biometrics',
  path: '/biometrics',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/biometrics.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const RecipesCreateLazyRoute = RecipesCreateLazyRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => RecipesLazyRoute,
} as any).lazy(() =>
  import('./routes/recipes.create.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/biometrics': typeof BiometricsLazyRoute
  '/coach': typeof CoachLazyRoute
  '/exercises': typeof ExercisesLazyRoute
  '/icon-generator': typeof IconGeneratorLazyRoute
  '/login': typeof LoginLazyRoute
  '/medical': typeof MedicalLazyRoute
  '/nutrition': typeof NutritionLazyRoute
  '/nutrition-coach': typeof NutritionCoachLazyRoute
  '/pain-tracker': typeof PainTrackerLazyRoute
  '/profile': typeof ProfileLazyRoute
  '/progress': typeof ProgressLazyRoute
  '/recipes': typeof RecipesLazyRouteWithChildren
  '/register': typeof RegisterLazyRoute
  '/wizard': typeof WizardLazyRoute
  '/workout': typeof WorkoutLazyRoute
  '/recipes/create': typeof RecipesCreateLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/biometrics': typeof BiometricsLazyRoute
  '/coach': typeof CoachLazyRoute
  '/exercises': typeof ExercisesLazyRoute
  '/icon-generator': typeof IconGeneratorLazyRoute
  '/login': typeof LoginLazyRoute
  '/medical': typeof MedicalLazyRoute
  '/nutrition': typeof NutritionLazyRoute
  '/nutrition-coach': typeof NutritionCoachLazyRoute
  '/pain-tracker': typeof PainTrackerLazyRoute
  '/profile': typeof ProfileLazyRoute
  '/progress': typeof ProgressLazyRoute
  '/recipes': typeof RecipesLazyRouteWithChildren
  '/register': typeof RegisterLazyRoute
  '/wizard': typeof WizardLazyRoute
  '/workout': typeof WorkoutLazyRoute
  '/recipes/create': typeof RecipesCreateLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/biometrics': typeof BiometricsLazyRoute
  '/coach': typeof CoachLazyRoute
  '/exercises': typeof ExercisesLazyRoute
  '/icon-generator': typeof IconGeneratorLazyRoute
  '/login': typeof LoginLazyRoute
  '/medical': typeof MedicalLazyRoute
  '/nutrition': typeof NutritionLazyRoute
  '/nutrition-coach': typeof NutritionCoachLazyRoute
  '/pain-tracker': typeof PainTrackerLazyRoute
  '/profile': typeof ProfileLazyRoute
  '/progress': typeof ProgressLazyRoute
  '/recipes': typeof RecipesLazyRouteWithChildren
  '/register': typeof RegisterLazyRoute
  '/wizard': typeof WizardLazyRoute
  '/workout': typeof WorkoutLazyRoute
  '/recipes/create': typeof RecipesCreateLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/biometrics'
    | '/coach'
    | '/exercises'
    | '/icon-generator'
    | '/login'
    | '/medical'
    | '/nutrition'
    | '/nutrition-coach'
    | '/pain-tracker'
    | '/profile'
    | '/progress'
    | '/recipes'
    | '/register'
    | '/wizard'
    | '/workout'
    | '/recipes/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/biometrics'
    | '/coach'
    | '/exercises'
    | '/icon-generator'
    | '/login'
    | '/medical'
    | '/nutrition'
    | '/nutrition-coach'
    | '/pain-tracker'
    | '/profile'
    | '/progress'
    | '/recipes'
    | '/register'
    | '/wizard'
    | '/workout'
    | '/recipes/create'
  id:
    | '__root__'
    | '/'
    | '/biometrics'
    | '/coach'
    | '/exercises'
    | '/icon-generator'
    | '/login'
    | '/medical'
    | '/nutrition'
    | '/nutrition-coach'
    | '/pain-tracker'
    | '/profile'
    | '/progress'
    | '/recipes'
    | '/register'
    | '/wizard'
    | '/workout'
    | '/recipes/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  BiometricsLazyRoute: typeof BiometricsLazyRoute
  CoachLazyRoute: typeof CoachLazyRoute
  ExercisesLazyRoute: typeof ExercisesLazyRoute
  IconGeneratorLazyRoute: typeof IconGeneratorLazyRoute
  LoginLazyRoute: typeof LoginLazyRoute
  MedicalLazyRoute: typeof MedicalLazyRoute
  NutritionLazyRoute: typeof NutritionLazyRoute
  NutritionCoachLazyRoute: typeof NutritionCoachLazyRoute
  PainTrackerLazyRoute: typeof PainTrackerLazyRoute
  ProfileLazyRoute: typeof ProfileLazyRoute
  ProgressLazyRoute: typeof ProgressLazyRoute
  RecipesLazyRoute: typeof RecipesLazyRouteWithChildren
  RegisterLazyRoute: typeof RegisterLazyRoute
  WizardLazyRoute: typeof WizardLazyRoute
  WorkoutLazyRoute: typeof WorkoutLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workout': {
      id: '/workout'
      path: '/workout'
      fullPath: '/workout'
      preLoaderRoute: typeof WorkoutLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wizard': {
      id: '/wizard'
      path: '/wizard'
      fullPath: '/wizard'
      preLoaderRoute: typeof WizardLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes': {
      id: '/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pain-tracker': {
      id: '/pain-tracker'
      path: '/pain-tracker'
      fullPath: '/pain-tracker'
      preLoaderRoute: typeof PainTrackerLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition-coach': {
      id: '/nutrition-coach'
      path: '/nutrition-coach'
      fullPath: '/nutrition-coach'
      preLoaderRoute: typeof NutritionCoachLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition': {
      id: '/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof NutritionLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical': {
      id: '/medical'
      path: '/medical'
      fullPath: '/medical'
      preLoaderRoute: typeof MedicalLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/icon-generator': {
      id: '/icon-generator'
      path: '/icon-generator'
      fullPath: '/icon-generator'
      preLoaderRoute: typeof IconGeneratorLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises': {
      id: '/exercises'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof ExercisesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biometrics': {
      id: '/biometrics'
      path: '/biometrics'
      fullPath: '/biometrics'
      preLoaderRoute: typeof BiometricsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/create': {
      id: '/recipes/create'
      path: '/create'
      fullPath: '/recipes/create'
      preLoaderRoute: typeof RecipesCreateLazyRouteImport
      parentRoute: typeof RecipesLazyRoute
    }
  }
}

interface RecipesLazyRouteChildren {
  RecipesCreateLazyRoute: typeof RecipesCreateLazyRoute
}

const RecipesLazyRouteChildren: RecipesLazyRouteChildren = {
  RecipesCreateLazyRoute: RecipesCreateLazyRoute,
}

const RecipesLazyRouteWithChildren = RecipesLazyRoute._addFileChildren(
  RecipesLazyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  BiometricsLazyRoute: BiometricsLazyRoute,
  CoachLazyRoute: CoachLazyRoute,
  ExercisesLazyRoute: ExercisesLazyRoute,
  IconGeneratorLazyRoute: IconGeneratorLazyRoute,
  LoginLazyRoute: LoginLazyRoute,
  MedicalLazyRoute: MedicalLazyRoute,
  NutritionLazyRoute: NutritionLazyRoute,
  NutritionCoachLazyRoute: NutritionCoachLazyRoute,
  PainTrackerLazyRoute: PainTrackerLazyRoute,
  ProfileLazyRoute: ProfileLazyRoute,
  ProgressLazyRoute: ProgressLazyRoute,
  RecipesLazyRoute: RecipesLazyRouteWithChildren,
  RegisterLazyRoute: RegisterLazyRoute,
  WizardLazyRoute: WizardLazyRoute,
  WorkoutLazyRoute: WorkoutLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
